# Tests distest on 3.9 only. Faster, so run every push
name: Run Tests (single version)

on:
  push:
    branches-ignore: [ develop, master, release/**]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .

      - name: Test with distest
        run: |
          ./run_tests.sh
        env:
          TARGET_ID: "582625299611648042"
          CHANNEL: "586041924129914910"
          TESTER_TOKEN: ${{ secrets.TESTER_TOKEN }}
          TARGET_TOKEN: ${{ secrets.TARGET_TOKEN }}


  test_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          clean: false
          fetch-depth: 20
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .
      - name: Test Docs
        run: ./test_sphinx.sh
        shell: bash